server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationcenterdb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: VACCINATION-CENTER-SERVICE
    
# This vaccination center automatically register in Eureka server using dependency which added in pom.xml,, so not required config here